<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_AnalogValue" Id="{33d6d243-fb08-490d-9495-c8eca3289fda}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_AnalogValue IMPLEMENTS I_Observer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_nActualValue		: BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="nValue" Id="{a61bde19-c47d-43bf-afc1-3803844d2ff4}">
      <Declaration><![CDATA[PROPERTY nValue : BYTE]]></Declaration>
      <Get Name="Get" Id="{1a940b24-2370-44d0-aa60-57f549af0c9e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[nValue := _nActualValue;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Update" Id="{9b5a5192-fb75-4a36-8565-4fb8512337b8}">
      <Declaration><![CDATA[METHOD Update : BYTE
VAR_INPUT
	nNewValue		: BYTE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_nActualValue := nNewValue;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_AnalogValue">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_AnalogValue.nValue.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_AnalogValue.Update">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>
